In [1]:
import numpy as np

In [2]:
x = [1, 2, 3, 4]

In [3]:
nx = np.array(x)

In [4]:
x = np.array([1, 2, 3, 4, 5])
print(x.ndim)     # dimention count
print(x.shape)    # shape of array
print(x.size)     # element count


1
(5,)
5


In [5]:
z = np.array([[1, 2, 3,],[3, 4, 5],[5, 6, 7]])
print(z.ndim)
print(z.shape)
print(z.size)
print(z)

2
(3, 3)
9
[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [6]:
from traceback import print_tb


a = np.arange(10,100,.1)
print(a.size)
a2 = a.reshape((30,30))
print(a2.shape)
a3 = a.reshape((30,15,2))

900
(30, 30)


In [7]:
b = np.linspace(1, 10, 100)
print(b)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [8]:
a = np.random.randint(1, 10,(3,3))
b = np.random.randint(1, 10,(3,3))
print(a)
print(b)
print(a+b)
print(a.max())
print(a.mean())
print(a.min())
print(a.std())
print(a.sum())
print(a.max(axis=0))   # pick rows
print(a.max(axis=1))   # pick column

[[2 8 5]
 [7 9 1]
 [2 4 7]]
[[9 6 4]
 [7 1 3]
 [3 7 8]]
[[11 14  9]
 [14 10  4]
 [ 5 11 15]]
9
5.0
1
2.748737083745107
45
[7 9 7]
[8 9 7]


In [9]:
t = np.arange(-np.pi * 3 , np.pi , 0.05)
x = np.sin(t)
y = np.cos(t)
print(x)
print(y)
print(np.pi)


[-3.67394040e-16 -4.99791693e-02 -9.98334166e-02 -1.49438132e-01
 -1.98669331e-01 -2.47403959e-01 -2.95520207e-01 -3.42897807e-01
 -3.89418342e-01 -4.34965534e-01 -4.79425539e-01 -5.22687229e-01
 -5.64642473e-01 -6.05186406e-01 -6.44217687e-01 -6.81638760e-01
 -7.17356091e-01 -7.51280405e-01 -7.83326910e-01 -8.13415505e-01
 -8.41470985e-01 -8.67423226e-01 -8.91207360e-01 -9.12763940e-01
 -9.32039086e-01 -9.48984619e-01 -9.63558185e-01 -9.75723358e-01
 -9.85449730e-01 -9.92712991e-01 -9.97494987e-01 -9.99783764e-01
 -9.99573603e-01 -9.96865028e-01 -9.91664810e-01 -9.83985947e-01
 -9.73847631e-01 -9.61275203e-01 -9.46300088e-01 -9.28959715e-01
 -9.09297427e-01 -8.87362369e-01 -8.63209367e-01 -8.36898791e-01
 -8.08496404e-01 -7.78073197e-01 -7.45705212e-01 -7.11473353e-01
 -6.75463181e-01 -6.37764702e-01 -5.98472144e-01 -5.57683717e-01
 -5.15501372e-01 -4.72030541e-01 -4.27379880e-01 -3.81660992e-01
 -3.34988150e-01 -2.87478012e-01 -2.39249329e-01 -1.90422647e-01
 -1.41120008e-01 -9.14646

In [ ]:
import matplotlib.pyplot as plt
plt.plot(t,x,'r--o')
plt.plot(t,y,'g:x')
plt.title("visualization")
plt.show


In [12]:
x = np.random.randint(1, 100, (6,6))
print(x)

[[31 91 85 50 50 50]
 [54 47 95 47 79 80]
 [31 64 45 22 59 21]
 [10 73 30 81 43 97]
 [68 93 45  3 41 39]
 [50  4 94 20 96 11]]


In [13]:
x[0]

array([31, 91, 85, 50, 50, 50])

In [14]:
x[0,1]

91

In [15]:
x[0,0]

31

In [17]:
x[2,3]

22

In [18]:
x[:,0]     # first column

array([31, 54, 31, 10, 68, 50])

In [24]:
x = np.array([[1, 2, 3, 4],[6, 4, 2, 2],[2, 3, 4, 3],[1, 2, 4, 1]])
print(x.ndim)
print(x.size)
print(x.shape)
print(x)

2
16
(4, 4)
[[1 2 3 4]
 [6 4 2 2]
 [2 3 4 3]
 [1 2 4 1]]


In [26]:
print(x[1:,0:3])


[[6 4 2]
 [2 3 4]
 [1 2 4]]
[[4 2 2]
 [3 4 3]]


In [27]:
print(x[1:3,1:])

[[4 2 2]
 [3 4 3]]
